apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: application-architect-anthropic
  namespace: default
  labels:
    app: application-architect-anthropic
    tier: agents
    agent-type: anthropic
    managed-by: argocd
    dependency-tier: "2"
  annotations:
    app.oam.dev/depends-on: "orchestration-service,redis-infrastructure,business-analyst-anthropic"
spec:
  components:
  - name: application-architect-knative-service
    type: raw
    properties:
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: application-architect-anthropic
        namespace: default
        labels:
          app: application-architect-anthropic
          version: v1.0.0
          agent-type: anthropic
          agent-role: application-architect
      spec:
        template:
          metadata:
            labels:
              app: application-architect-anthropic
              version: v1.0.0
            annotations:
              autoscaling.knative.dev/minScale: "0"
              autoscaling.knative.dev/maxScale: "3"
              autoscaling.knative.dev/target: "70"
              autoscaling.knative.dev/scaleToZeroGracePeriod: "300s"
          spec:
            serviceAccountName: default
            containers:
            - name: application-architect-anthropic
              image: socrates12345/application-architect-anthropic:latest
              ports:
              - containerPort: 8080
                protocol: TCP
              env:
              - name: LOG_LEVEL
                value: "INFO"
              - name: REDIS_URL
                value: "redis://redis-service:6379"
              - name: ORCHESTRATION_SERVICE_URL
                value: "http://orchestration-service.default.svc.cluster.local"
              - name: AGENT_ROLE
                value: "application-architect"
              - name: AGENT_TYPE
                value: "anthropic"
              - name: BUSINESS_ANALYST_URL
                value: "http://business-analyst-anthropic.default.svc.cluster.local"
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "200m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 30
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 15

  policies:
  - name: dependency-policy
    type: topology
    properties:
      namespace: default
      if: "status.phase != 'Running'"
      message: "Waiting for business analyst and orchestration services"

  workflow:
    steps:
    - name: check-dependencies
      type: step-group
      subSteps:
      - name: check-business-analyst
        type: read-object
        properties:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: business-analyst-anthropic
          namespace: default
      - name: check-orchestration
        type: read-object
        properties:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: orchestration-service
          namespace: default
    - name: deploy-application-architect
      type: apply-component
      properties:
        component: application-architect-knative-service
    - name: verify-agent-ready
      type: wait-for-healthy
      properties:
        component: application-architect-knative-service
        timeout: 300s