apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: solution-architect-anthropic
  namespace: default
  labels:
    app: solution-architect-anthropic
    tier: agents
    agent-type: anthropic
    managed-by: argocd
    dependency-tier: "4"
  annotations:
    app.oam.dev/depends-on: "infrastructure-architect-anthropic,application-architect-anthropic,business-analyst-anthropic"
spec:
  components:
  - name: solution-architect-knative-service
    type: raw
    properties:
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: solution-architect-anthropic
        namespace: default
        labels:
          app: solution-architect-anthropic
          version: v1.0.0
          agent-type: anthropic
          agent-role: solution-architect
      spec:
        template:
          metadata:
            labels:
              app: solution-architect-anthropic
              version: v1.0.0
            annotations:
              autoscaling.knative.dev/minScale: "0"
              autoscaling.knative.dev/maxScale: "2"
              autoscaling.knative.dev/target: "70"
              autoscaling.knative.dev/scaleToZeroGracePeriod: "300s"
          spec:
            serviceAccountName: default
            containers:
            - name: solution-architect-anthropic
              image: socrates12345/solution-architect-anthropic:latest
              ports:
              - containerPort: 8080
                protocol: TCP
              env:
              - name: LOG_LEVEL
                value: "INFO"
              - name: REDIS_URL
                value: "redis://redis-service:6379"
              - name: ORCHESTRATION_SERVICE_URL
                value: "http://orchestration-service.default.svc.cluster.local"
              - name: AGENT_ROLE
                value: "solution-architect"
              - name: AGENT_TYPE
                value: "anthropic"
              - name: BUSINESS_ANALYST_URL
                value: "http://business-analyst-anthropic.default.svc.cluster.local"
              - name: APPLICATION_ARCHITECT_URL
                value: "http://application-architect-anthropic.default.svc.cluster.local"
              - name: INFRASTRUCTURE_ARCHITECT_URL
                value: "http://infrastructure-architect-anthropic.default.svc.cluster.local"
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "300m"
                limits:
                  memory: "1Gi"
                  cpu: "600m"
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 30
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 15

  policies:
  - name: dependency-policy
    type: topology
    properties:
      namespace: default
      if: "status.phase != 'Running'"
      message: "Waiting for all architect agents to be ready"

  workflow:
    steps:
    - name: check-all-architects
      type: step-group
      subSteps:
      - name: check-business-analyst
        type: read-object
        properties:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: business-analyst-anthropic
          namespace: default
      - name: check-application-architect
        type: read-object
        properties:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: application-architect-anthropic
          namespace: default
      - name: check-infrastructure-architect
        type: read-object
        properties:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: infrastructure-architect-anthropic
          namespace: default
    - name: deploy-solution-architect
      type: apply-component
      properties:
        component: solution-architect-knative-service
    - name: verify-agent-ready
      type: wait-for-healthy
      properties:
        component: solution-architect-knative-service
        timeout: 300s