apiVersion: v1
kind: ConfigMap
metadata:
  name: test-service-default-config
  namespace: health-service-idp
data:
  APP_ENV: "production"
  SERVICE_NAME: "test-service-default"
  DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@health-service-idp-postgres-rw.health-service-idp.svc.cluster.local:5432/test-service-default"
  REDIS_URL: "redis://:$REDIS_PASSWORD@health-service-idp-redis-master.health-service-idp.svc.cluster.local:6379/0"
