apiVersion: v1
kind: ConfigMap
metadata:
  name: fintech-realtime-manual-config
  namespace: health-service-idp
data:
  APP_ENV: "production"
  SERVICE_NAME: "fintech-realtime-manual"
  DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@health-service-idp-postgres-rw.health-service-idp.svc.cluster.local:5432/fintech-realtime-manual"
  REDIS_URL: "redis://:$REDIS_PASSWORD@health-service-idp-redis-master.health-service-idp.svc.cluster.local:6379/0"
