apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-realtime-test-config
  namespace: health-service-idp
data:
  APP_ENV: "production"
  SERVICE_NAME: "retail-realtime-test"
  DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@health-service-idp-postgres-rw.health-service-idp.svc.cluster.local:5432/retail-realtime-test"
  REDIS_URL: "redis://:$REDIS_PASSWORD@health-service-idp-redis-master.health-service-idp.svc.cluster.local:6379/0"
