apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: streamlit-frontend
  namespace: default
  labels:
    app: streamlit-frontend
    tier: frontend
    managed-by: argocd
    dependency-tier: "5"
  annotations:
    app.oam.dev/depends-on: "orchestration-service,solution-architect-anthropic"
spec:
  components:
  - name: streamlit-frontend-knative-service
    type: raw
    properties:
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: streamlit-frontend
        namespace: default
        labels:
          app: streamlit-frontend
          version: v1.0.0
          service-type: frontend
      spec:
        template:
          metadata:
            labels:
              app: streamlit-frontend
              version: v1.0.0
            annotations:
              autoscaling.knative.dev/minScale: "1"
              autoscaling.knative.dev/maxScale: "3"
              autoscaling.knative.dev/target: "80"
              autoscaling.knative.dev/scaleToZeroGracePeriod: "600s"
          spec:
            serviceAccountName: default
            containers:
            - name: streamlit-frontend
              image: socrates12345/streamlit-frontend:latest
              ports:
              - containerPort: 8501
                protocol: TCP
              env:
              - name: LOG_LEVEL
                value: "INFO"
              - name: ORCHESTRATION_SERVICE_URL
                value: "http://orchestration-service.default.svc.cluster.local"
              - name: BUSINESS_ANALYST_URL
                value: "http://business-analyst-anthropic.default.svc.cluster.local"
              - name: APPLICATION_ARCHITECT_URL
                value: "http://application-architect-anthropic.default.svc.cluster.local"
              - name: INFRASTRUCTURE_ARCHITECT_URL
                value: "http://infrastructure-architect-anthropic.default.svc.cluster.local"
              - name: SOLUTION_ARCHITECT_URL
                value: "http://solution-architect-anthropic.default.svc.cluster.local"
              - name: REDIS_URL
                value: "redis://redis-service:6379"
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "300m"
                limits:
                  memory: "1Gi"
                  cpu: "600m"
              livenessProbe:
                httpGet:
                  path: /_stcore/health
                  port: 8501
                initialDelaySeconds: 60
                periodSeconds: 30
                timeoutSeconds: 10
              readinessProbe:
                httpGet:
                  path: /_stcore/health
                  port: 8501
                initialDelaySeconds: 30
                periodSeconds: 15
                timeoutSeconds: 5

  policies:
  - name: dependency-policy
    type: topology
    properties:
      namespace: default
      if: "status.phase != 'Running'"
      message: "Waiting for orchestration service and agent services"

  - name: health-policy
    type: health
    properties:
      probeInterval: 60
      probeTimeout: 15

  workflow:
    steps:
    - name: check-backend-dependencies
      type: step-group
      subSteps:
      - name: check-orchestration
        type: read-object
        properties:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: orchestration-service
          namespace: default
      - name: check-solution-architect
        type: read-object
        properties:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: solution-architect-anthropic
          namespace: default
    - name: deploy-frontend
      type: apply-component
      properties:
        component: streamlit-frontend-knative-service
    - name: verify-frontend-ready
      type: wait-for-healthy
      properties:
        component: streamlit-frontend-knative-service
        timeout: 600s