apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: architecture-tool-app-of-apps
  namespace: argocd
  labels:
    app: architecture-tool
    type: app-of-apps
    tier: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shlapolosa/health-service-idp
    targetRevision: HEAD
    path: argocd-apps
    directory:
      recurse: true
      include: "*-argocd-app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
  - name: Description
    value: Application of Applications for Visual Architecture Maintenance Tool
  - name: Components
    value: Infrastructure, Orchestration, Agents, Frontend
  - name: Deployment Order
    value: "Tier 0: Redis -> Tier 1: Orchestration -> Tier 2: Business/App Architects -> Tier 3: Infrastructure Architect -> Tier 4: Solution Architect -> Tier 5: Frontend"