apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: oam-e2e-fixtest-155157
  namespace: default
spec:
  components:
  - name: oam-e2e-fixtest-155157-svc
    type: webservice
    properties:
      language: python
