apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: patient3-api
  namespace: default
spec:
  components:
  - name: patient3-db
    type: postgresql
    properties:
      database: patients
      storageClass: default
  - name: patient3-cache
    type: redis
    properties:
      architecture: standalone
      persistenceEnabled: false
  - name: patient3-auth0
    type: auth0-idp
    properties: {}
  - name: patient3-api
    type: webservice
    properties:
      name: patient3-api
      language: python
      database: patient3-db
      cache: patient3-cache
      identity: patient3-auth0
    traits:
    - type: expose-api
      properties:
        identity: patient3-auth0
  - name: patient3-identity
    type: webservice
    properties:
      name: patient3-identity
      language: java
      database: patient3-db
      cache: patient3-cache
      identity: patient3-auth0
    traits:
    - type: auto-scaffold-bootstrap
      properties:
        language: java
    - type: expose-api
      properties:
        identity: patient3-auth0
