apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: patient2-api
  namespace: default
spec:
  components:
  - name: patient2-db
    type: postgresql
    properties:
      database: patients
      storageClass: default
  - name: patient2-cache
    type: redis
    properties:
      architecture: standalone
      persistenceEnabled: false
  - name: patient2-auth0
    type: auth0-idp
    properties: {}
  - name: patient2-api
    type: webservice
    properties:
      name: patient2-api
      language: python
      database: patient2-db
      cache: patient2-cache
      identity: patient2-auth0
    traits:
    - type: expose-api
      properties:
        identity: patient2-auth0
