apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: spine-e2e-svc
  namespace: default
spec:
  components:
  - name: spine-e2e-svc
    type: webservice
    properties:
      name: spine-e2e-svc
      language: python
      environment:
        E2E_UPDATE_MARKER: "phase2"
