apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-architect-anthropic
  namespace: argocd
  labels:
    app: application-architect-anthropic
    tier: agents
    agent-type: anthropic
    dependency-tier: "2"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shlapolosa/health-service-idp
    targetRevision: HEAD
    path: oam-applications/agents
    directory:
      include: "application-architect-app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
  - name: Description
    value: Application Architect Anthropic Agent
  - name: Dependencies
    value: business-analyst-anthropic, orchestration-service