apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: orchestration-service
  namespace: default
  labels:
    app: orchestration-service
    tier: orchestration
    dependency-tier: "1"
spec:
  components:
  - name: orchestration-knative-service
    type: raw
    properties:
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: orchestration-service
        namespace: default
        labels:
          app: orchestration-service
          version: v1.0.0
      spec:
        template:
          metadata:
            labels:
              app: orchestration-service
              version: v1.0.0
            annotations:
              autoscaling.knative.dev/minScale: "1"
              autoscaling.knative.dev/maxScale: "2"
          spec:
            containers:
            - name: orchestration-service
              image: socrates12345/orchestration-service:latest
              ports:
              - containerPort: 8080
              env:
              - name: LOG_LEVEL
                value: "INFO"
              - name: REDIS_URL
                value: "redis://redis-service:6379"
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "150m"
                limits:
                  memory: "512Mi"
                  cpu: "300m"
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 30
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 15